Feat#1 회원가입 화면 구현
Customlms/Frontend pull request #2
Opened 2022-01-18 14:21 UTC by YUN-GYEONG

# 주제
- 회원가입 화면 구현

# 작업 완료 내용 (자세히 작성)
- **회원가입**(`/signup`) 화면 구현
- **회원조회**(`/find-user`) 화면 구현

# 관련 이슈 번호
✅ Close #1 

# 미작업 내용
- **로그인 페이지** (`/login`)

# 주의사항
[ ]

2022-01-18 14:29 UTC, devsungmin requested changes
제가 comment 남긴 부분 답변 달아주시고 코드 수정 부탁드립니다 :) 👍🏼

2022-01-18 14:29 UTC, devsungmin commented on pages/find-user/index.tsx
> +// }
PR요청시 주석 삭제 해주시면 좋습니다 ~

2022-01-18 14:29 UTC, devsungmin commented on pages/find-user/index.tsx
> +      <div>
Class와 id값 추가 헤주세요!

2022-01-18 14:29 UTC, devsungmin commented on pages/login/index.tsx
> +        <div>
class 명시 부탁드립니다 :)

2022-01-18 14:29 UTC, devsungmin commented on pages/signup/index.tsx
> +        <div>
여기도 class 지정 부탁드립니다.

2022-01-18 14:29 UTC, devsungmin commented on pages/signup/index.tsx
> +                    <InputLabel htmlFor="my-input">이메일</InputLabel>
htmlFor 값이 다 같은 이유가 있을까요?

2022-01-18 14:29 UTC, devsungmin commented on pages/signup/index.tsx
> +                    <FormHelperText id="my-helper-text"></FormHelperText>
id값이 다 같은 이유가 있을까요?

2022-01-18 14:29 UTC, devsungmin commented on pages/find-user/index.tsx
> +                <FormHelperText id="my-helper-text"></FormHelperText>
여기도 id값이 왜 같은 건가요??

2022-01-18 14:29 UTC, devsungmin commented on pages/find-user/index.tsx
> +                <Input id="Name" aria-describedby="my-helper-text" />
여기도 왜 다 값이 name 값인가요??

2022-01-18 14:59 UTC, Soong-moo approved these changes

2022-01-19 06:16 UTC, YUN-GYEONG commented on pages/find-user/index.tsx
> +// }
네, 수정하도록 하겠습니다~!

2022-01-25 12:50 UTC, YUN-GYEONG commented on pages/find-user/index.tsx
> +      <div>
@devsungmin Class가 html 안의 class 를 의미하는건가요? 아니면 React 상에서 컴포넌트 형태로 만드는 것을 의미하는건가요?

2022-01-25 13:55 UTC, devsungmin reviewed
`대학원` 부분 줄 내려가는거 수정 부탁드립니다 :)

<img width="676" alt="스크린샷 2022-01-25 오후 10 46 11" src="https://user-images.githubusercontent.com/37958836/150989941-8068f653-1ee0-417a-85bb-d00080680907.png">

2022-01-25 13:55 UTC, devsungmin commented on pages/signup/index.tsx
> +                <Input id="password" aria-describedby="passwordHelperText" />
```suggestion
                <Input id="password" aria-describedby="passwordHelperText" type="password"/>
```
타입을 password로 선언하면 ****로 표시 됩니다.

<img width="166" alt="스크린샷 2022-01-25 오후 10 51 09" src="https://user-images.githubusercontent.com/37958836/150989300-0cc1abac-ac27-43ef-9d7c-4a896e6943eb.png">

2022-01-25 13:55 UTC, devsungmin commented on pages/signup/index.tsx
> +                <Input id="passwordCheck" aria-describedby="passwordCheckHelperText" />
```suggestion
                <Input id="passwordCheck" aria-describedby="passwordCheckHelperText" type="password"/>
```

2022-01-25 13:55 UTC, devsungmin commented on pages/signup/index.tsx
> +                <Input id="email" aria-describedby="emailHelperText" />
이런 경우 이메일을 처음부터 끝까지 써야하니 @이후 나오는 gmail.com 같은 값은 드롭다운을 사용해서 하는 걸 추천 드립니다 :)

mui에서는 `< Menu />` 태그를 사용하면 될 겁니다.

2022-01-26 05:52 UTC, YUN-GYEONG commented on pages/signup/index.tsx
> +                <Input id="password" aria-describedby="passwordHelperText" />
넵 수정하겠습니당

2022-01-26 09:17 UTC, YUN-GYEONG commented on pages/signup/index.tsx
> +                <Input id="email" aria-describedby="emailHelperText" />
넵 찾아보고 적용해보겠습니다 !

2022-02-02 07:19 UTC, devsungmin approved these changes
LGTM

2022-02-04 13:55 UTC, merged