feat#3 ID/PW 찾기 화면 구현
Customlms/Frontend pull request #4
Opened 2022-01-19 13:23 UTC by Soong-moo

# 주제
- ID/PW 찾기 화면 구현

# 작업 완료 내용 (자세히 작성)
- **ID/PW 찾기**(`/findAccount`) 화면 구현

# 관련 이슈 번호
✅ Close #3

# 미작업 내용
- **로그인 페이지** (`/login`)

# 주의사항
[ ]

2022-01-19 14:04 UTC, devsungmin requested changes
도메인 값은 카멜 케이스를 사용하지 않습니다!

2022-01-19 14:04 UTC, devsungmin commented on pages/findAccount/findId.tsx
> +            <Button href="/logIn">로그인</Button>
```suggestion
            <Button href="/login">로그인</Button>
```

2022-01-19 14:04 UTC, devsungmin commented on pages/findAccount/findId.tsx
> +            <Button href="/findAccount">비밀번호 찾기</Button>
```suggestion
            <Button href="/find/passwd">비밀번호 찾기</Button>
```

2022-01-19 14:04 UTC, devsungmin commented on pages/findAccount/findPw.tsx
> +            <Button href="/logIn">로그인</Button>
```suggestion
            <Button href="/login">로그인</Button>
```

2022-01-19 14:04 UTC, devsungmin commented on pages/findAccount/index.tsx
> +  Router.push("/findAccount/findId")
```suggestion
  Router.push("/find/id")
```

2022-01-19 14:04 UTC, devsungmin commented on pages/findAccount/index.tsx
> +  Router.push("/findAccount/findPw")
```suggestion
  Router.push("/find/passwd")
```

2022-01-19 14:04 UTC, devsungmin commented on pages/findAccount/index.tsx
> +            <TextField id="number" label="학번/사번" variant="outlined" />
id값을 조금 더 좋은 네이밍이 있을 것 같습니다.

2022-01-25 14:03 UTC, devsungmin reviewed
한 화면 id/pw찾기를 같이 하는 사이트가 있나요...??
<img width="393" alt="스크린샷 2022-01-25 오후 11 02 41" src="https://user-images.githubusercontent.com/37958836/150991119-2abe8c3b-3c2c-4680-9dc1-4820cc826d4c.png">

2022-01-25 14:05 UTC, Soong-moo commented
> 한 화면 id/pw찾기를 같이 하는 사이트가 있나요...?? <img alt="스크린샷 2022-01-25 오후 11 02 41" width="393" src="https://user-images.githubusercontent.com/37958836/150991119-2abe8c3b-3c2c-4680-9dc1-4820cc826d4c.png"> 에

2022-01-26 23:10 UTC, devsungmin approved these changes
LGTM

2022-02-04 12:58 UTC, YUN-GYEONG approved these changes

2022-02-04 12:59 UTC, merged